### ISSUE TITLE
[Suggestion] Docker image

### ISSUE THREAD

**Issue by Mattssn** [X-Ryl669/kutr#14]
I am not sure if this project is still active but if so what a docker image for us folks in the land of containers? there are a few for the official Koel repo, but I am liking your feature additions!

**Comment by X-Ryl669** [comment]
I'm not sure either. I'm still using Kutr every day for my music, but I've kind of stopped maintaining the changes from upstream since it was too time consuming and I have all the features I wanted initially.

If I find the time to, I'll try to create a docker image (never done that before, if it's not too painful, I'll have a look to it).

**Comment by RomeSilvanus** [comment]
I second that. I tried making a Docker image for myself but somehow everything constantly broke.
:'c 

I still prefer your fork over Koel since the guest login is a thing here.
