### ISSUE TITLE
Redirection

### ISSUE THREAD

**Issue by popouille** [X-Ryl669/kutr#8]
Hello,
on fresh installation mydomain.com redirect me to mydomain.com/loginRedir.php with onst USING_CMS set on "false".

**Comment by X-Ryl669** [comment]
That's strange. The only piece of code using `loginRedir.php` are under `if(USING_CMS)` section.
I wonder if you have correctly rebuilt the application's javascript stuff. Did you run `yarn dev` to rebuild it ?

**Comment by popouille** [comment]
In  my logs i have this:
`PHP Notice:  Undefined index: REMOTE_AUTH_LOGOUT_URL                 in /var/www/vhosts/***/httpdocs/***/loginRedir.php on line 20
[Thu May  3 00:52:39 2018] PHP Notice:  Undefined index: REMOTE_AUTH_SECRET in /                var/www/vhosts/***/httpdocs/***/loginRedir.php on line 22`

It looking for  REMOTE_AUTH_LOGOUT_URL and REMOTE_AUTH_SECRET with USING_CMS set to false ?

**Comment by X-Ryl669** [comment]
You should not be redirected to `loginRedir.php` if `USING_CMS` is false, so these errors should not happen. Where did you write `USING_CMS=false` ? Did you change the code in `resources/assets/js/app.vue` (search for USING_CMS in that file) ? That's where it should be changed.

If you did it, you must re-run `yarn dev` in your main folder to recompile the javascript code.
Then you can check it was correctly applied because the login dialog will pop up in that case.

**Comment by popouille** [comment]
Oh ok i recompiled js and it works now.

**Comment by X-Ryl669** [comment]
Great!
